import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { CartProvider } from "../context/page";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
        <Navbar />
        {children}
        <Footer />
        </CartProvider>
        </body>
    </html>
  );
}
